# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('imagename', models.CharField(max_length=150)),
            ],
        ),
    ]
