# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentalunit',
            name='parentStuff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
