# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
