# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0002_auto_20170718_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date_of', models.DateTimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date_assigned', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItemAssignedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='parentalunit',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pta.Teacher'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='parentalUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pta.ParentalUnit'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.Teacher'),
        ),
        migrations.AddField(
            model_name='todoitemassignedto',
            name='assignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.ParentalUnit'),
        ),
        migrations.AddField(
            model_name='todoitemassignedto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.TodoItem'),
        ),
    ]
