# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0003_auto_20170718_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name_plural': 'Homework'},
        ),
    ]
