# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0004_auto_20170718_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageBody', models.TextField()),
                ('dateOf', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.Message')),
                ('parentalunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.ParentalUnit')),
            ],
        ),
    ]
